# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Graph": "00_core.ipynb",
         "AdjacencyMatrixGraph": "00_core.ipynb",
         "Node": "00_core.ipynb",
         "AdjacencySetGraph": "00_core.ipynb",
         "asg": "00_core.ipynb",
         "breadth_first": "01_traversal.ipynb",
         "depth_first": "01_traversal.ipynb"}

modules = ["core.py",
           "traversal.py"]

doc_url = "https://ddobrinskiy.github.io/graph_utils/"

git_url = "https://github.com/ddobrinskiy/graph_utils/tree/master/"

def custom_doc_links(name): return None
