# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Graph": "00_core.ipynb",
         "AdjacencyMatrixGraph": "00_core.ipynb",
         "Node": "00_core.ipynb",
         "AdjacencySetGraph": "00_core.ipynb",
         "breadth_first": "01_traversal.ipynb",
         "depth_first": "01_traversal.ipynb",
         "topological_sort": "02_topological_sort.ipynb",
         "Row": "05_Prim_spanning_tree.ipynb",
         "build_distance_table": "04_dijsktra.ipynb",
         "shortest_path": "03_shortest_path.ipynb",
         "priority_dict": "04_dijsktra.ipynb",
         "spanning_tree": "06_Kruskal_spanning_tree.ipynb",
         "has_cycle": "06_Kruskal_spanning_tree.ipynb"}

modules = ["core.py",
           "traversal.py",
           "top_sort.py",
           "shortest_path.py",
           "dijsktra.py",
           "prim.py",
           "kruskal.py"]

doc_url = "https://ddobrinskiy.github.io/graph_utils/"

git_url = "https://github.com/ddobrinskiy/graph_utils/tree/master/"

def custom_doc_links(name): return None
